version: "3.7"
services:
  # container name
  smokeping-master:
          container_name: smokeping-master
          # which image to pull
          image: handymenny/docker-smokeping:latest
          # set a hostname so that master-slave communication works correctly
          hostname: smokeping-master
          # pass data to the container as environment variables
          environment:
            # file owner id
            - PUID=0
            # group owner id
            - PGID=0
            # timezone
            - TZ=Europe/Bucharest
            # extra smokeping flags passed to the smokeping daemon
            - SMOKEPING_EXTRA_FLAGS="--debug-daemon"

          # persistent data paths, configuration, overrides
          volumes:
                  # the directory where the RRD data persists -> /data
                  - /opt/smokeping/data:/data
                  # the configuration directory -> /config
                  # map to an empty host directory to get generic configuration
                  - /opt/smokeping/etc:/config
                  # the smokeping_secrets file (needed for master/slave)
                  - /opt/smokeping/etc/smokeping_secrets:/etc/smokeping/etc/smokeping_secrets
                  # if you want web interface basic authentication add a
                  # .htaccess that points to a htpasswd generated file
                  - /opt/smokeping/apache/.htaccess:/var/www/html/smokeping/.htaccess
                  # the htpasswd generated file can live anywhere (is pointed
                  # to by the .htaccess)
                  - /opt/smokeping/apache/smokeping-access:/smokeping-access
          ports:
                  # on which host port should I expose the apache webserver
                  # (master only)
                  - "33196:80"
          restart: always
          network_mode: bridge

